#' Apply namespace prefixes to files
#'
#' @inheritParams namespacify
#' @param file character string of filepath for file to apply prefixes to.
#' @param vec.replacement Vector of patterns to replace; vector names are what should be replaced. Typically generated by
#' `make_prefix_vector`.
#'
#' @return none
#'
namespacify_file = function(
    file,
    vec.replacement,
    verbose = TRUE
){
  original.text = readLines(file, warn = FALSE)
  new.text = namespacify_text(original.text, vec.replacement)
  writeLines(new.text, file)
  if(verbose){
    cli::cli_div(theme = list(span.emph = list(color = "forestgreen")))
    cli::cli_text("-> {.emph {file}} namespacified! {sum(original.text != new.text)} lines changed")
  }
}
